services:
  - type: web
    name: logical-ability-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        value:  AIzaSyDm1y_Pjd_SGWoZ0kkyVta8tcsnPjFFCiE
